config/routes.rb
CodeShare::Application.routes.draw do

  resources :codes
  root :to => 'home#index'
  
  match "/about" => "home#about"
  match "/list" => "home#list"

  match "/share" => "code#share"
  match "/code/new" => "code#new"

  match "/code/show" => "code#show"
  match "/code/show/:id" => "code#show", :as => "show"

  match "/code/:id/version" => "code#versions", :as => "versions"
  match "/code/:code_id/v/:id" => "code#show_version", :as => "version_show"

  match "/comment/new/:id" => "comment#new"
  match "/code/edit/:id" => "code#edit", :as => "edit"
  match "/code/edit_commit" => "code#edit_commit"
 
end

app/models/code.rb
class Code < ActiveRecord::Base
  attr_accessible :author, :email, :page, :password
  validates :author, :email, :password, :presence => true
  has_many :snippets
  has_many :comments
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  attr_accessible :content, :email, :nick, :page
  belongs_to :code
  validates :email, :nick, :content, :presence => true
end

app/models/snippet.rb
class Snippet < ActiveRecord::Base
  attr_accessible :description, :language, :name, :source, :version
  belongs_to :code
  validates :description, :language, :name, :source, :version, :presence => true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  def not_found
    raise ActionController::RoutingError.new('Not Found')
  end
  def render_404
    raise ActionController::RoutingError.new('Not Found')
  end

end

app/controllers/code_controller.rb
class CodeController < ApplicationController
  include CodeHelper

  def share
    @code = Code.new
    @snippet = Snippet.new
  end

  def show
    begin 
      @code = Code.find(params[:id])
      @snippet = Snippet.where(:code_id => @code[:id]).last
      @comments = Comment.where(:code_id => @code[:id])
    rescue ActiveRecord::RecordNotFound
    end
  end

  def new
    if params[:code][:password] == "" || params[:code][:password] == nil
      render :action => :share, :code => params[:code], :snippet => params[:snippet]
      return
    end
    @code = get_code(params[:code])
    if @code.save
      @snippet = get_snippet(params[:snippet], @code[:id])
    else
      render :action => :share, :code => params[:code], :snippet => params[:snippet]
      return
    end
    if @snippet.save
      redirect_to "/code/show/#{@code[:id]}"
    else
      render :action => :share, :code => params[:code], :snippet => params[:snippet]
    end
  end

  def versions
    begin
      @code = Code.find(params[:id])
      @snippets = Snippet.where(:code_id => @code[:id])
    rescue ActiveRecord::RecordNotFound
    end
  end

  def show_version
    begin
      @code = Code.find(params[:code_id])
      @snippet = Snippet.where(:code_id => @code[:id], :version => params[:id])[0]
      @comments = Comment.where(:code_id => @code[:id])
    rescue ActiveRecord::RecordNotFound
    end
    render :show
  end

  def edit
    @snippet = Snippet.where(:code_id=>params[:id]).last
  end

  def edit_commit
    pwd = Code.find(params[:snippet][:code_id]).password
    if not validate(params[:code][:password], pwd)
      redirect_to "/code/show/#{params[:snippet][:code_id]}"
      return
    end
    @snippet = Snippet.new
    @snippet = get_snippet(params[:snippet], params[:snippet][:code_id], params[:snippet][:version].to_i + 1)
    @snippet.save
    redirect_to "/code/show/#{@snippet[:code_id]}"
  end

end

app/controllers/comment_controller.rb
class CommentController < ApplicationController

  def new
    @comment = Comment.new

    @comment[:code_id] = params[:id]
    @comment[:email] = params[:comment][:email]
    @comment[:nick] = params[:comment][:nick]
    @comment[:content] = params[:comment][:content]
    @comment[:page] = params[:comment][:page] if params[:comment][:page] != "" && params[:comment][:page] != nil
    
    if params[:comment][:page] != "" && params[:comment][:page] != nil
      if params[:comment][:page] =~ /http:\/\//
        @comment[:page] = params[:comment][:page]
      else
        @comment[:page] = "http://#{params[:comment][:page]}"
      end
    end

    @comment.save
    redirect_to "/code/show/#{@comment[:code_id]}"
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    snippets = Snippet.select("code_id, max(id)").group("code_id").limit(10)

    @latest = []
    snippets.reverse_each do |snippet| 
      @latest.append Snippet.where(:code_id=>snippet[:code_id]).order('id desc').last
    end

    code_comment = Hash.new(0)
    Comment.all.each do |comment|
      code_comment[comment[:code_id]] += 1
    end
    code_comment = code_comment.sort { |x ,y| ((y[1] <=> x[1]) << 1) + (y[0] <=> x[0]) }
    @hottest = []
    code_comment.each { |k, v| @hottest.append([Snippet.where(:code_id=>k).first, v])}
  end

  def list
    # snippets = Snippet.order('created_at desc').select('code_id').uniq
    snippets = Snippet.select("code_id, max(created_at)").group(:code_id)

    @codes = []
    snippets.reverse_each do |snippet|
      code = []
      code.append(Snippet.where(:code_id=>snippet[:code_id]).last)
      code.append(Code.where(:id=>snippet[:code_id]).first)
      @codes.append(code)
    end
  end

  def show
    id = params[:id]
    redirect_to "/code/show/#{id}" if id
  end

  def about
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

  def show_code(code, language)
    t = CodeRay.scan(code, language).div(:tab_width=>4, :line_numbers=>:table)
    t.html_safe
  end

  def markdown(text)
    options = {
      :autolink => true,
      :space_after_headers => true,
      :fenced_code_blocks => true,
      :no_intra_emphasis => true,
      :hard_wrap => true,
      :strikethrough => true
    }
    markdown = Redcarpet::Markdown.new(HtmlWithCodeRay, options)
    markdown.render(text).html_safe
  end

  class HtmlWithCodeRay < Redcarpet::Render::HTML
    def block_code(code, language)
      CodeRay.scan(code, language).div(:tab_width=>2)
    end
  end

  def gravatar_for email, options = {}
    options = {:alt => 'avatar', :class => 'avatar', :size => 80}.merge! options
    id = Digest::MD5::hexdigest email.strip.downcase
    url = 'http://www.gravatar.com/avatar/' + id + '.jpg?s=' + options[:size].to_s
    options.delete :size
    image_tag url, options
end

end

app/helpers/code_helper.rb
module CodeHelper

  require 'digest/md5'

  def encrypt(text, salt=nil)
    salt = (('0'..'9').to_a + ('a'..'z').to_a).shuffle[0..7].join if salt == nil
    enc = Digest::MD5.hexdigest(text)
    salt + enc
  end

  def validate(text, encrypted)
    salt = encrypted[0..7]
    encrypt(text, salt) == encrypted
  end

  def get_code(params)
    code = Code.new
    code[:author] = params[:author]
    code[:email] = params[:email]
    code[:password] = encrypt(params[:password])

    if params[:page] != "" && params[:page] != nil
      if params[:page] =~ /http:\/\//
        code[:page] = params[:page]
      else
        code[:page] = "http://#{params[:page]}"
      end
    end
    
    code
  end

  def get_snippet(params, code_id, version=1)
    snippet = Snippet.new
    snippet[:code_id] = code_id
    snippet[:description] = params[:description]
    snippet[:name] = params[:name]
    snippet[:source] = params[:source]
    snippet[:version] = version

    postfix = /[^.]+$/.match(snippet[:name])
    if postfix then
      postfix = postfix[0]
    else
      return Snippet.new
    end
    snippet[:language] = case postfix
    when "py" then "python"
    when "rb" then "ruby"
    when "c" then "c"
    when "cpp", "cc" then "cpp"
    when "yaml" then "yaml"
    when "pl" then "perl"
    when "cs" then "c#"
    when "java" then "java"
    else "text"
    end

    puts "*********   get_snippet   ***************"
    puts snippet[:language]
    puts "*********   get_snippet   *************************"
    snippet
  end

end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/code/edit.html.erb
<div class="row">
    <div class="span12">
    <%= form_tag({:action=>"edit_commit", :controller=>"code"}, :method=>"post", :multipart=>"true") do %>
        <div class="row">
            <div class="span7">
                <h2>The Code</h2>
                <div class="row">
                    <div class="span7 note">Passwor, if null or wrong, the code will not change</div>
                    <div class="span3">
                        <%= text_field :code, :password, :class=>"span3", :placeholder=>"Password" %>
                    </div>
                </div>
                
                <%= text_field :snippet, :description, :class=>"span7" %>
                <%= text_field :snippet, :name, :class=>"span4" %>
                <%= text_area :snippet, :source, :class=>"code-write span7", :rows=>"15" %>
                <%= text_field :snippet, :code_id, :class=>"none" %>
                <%= text_field :snippet, :version, :class=>"none" %>
                <input type="submit" class="btn-primary span3" value="Commit" />
                <input type="reset" class="btn-primary span2" value="Cancel" />
            </div>
        </div>
    <% end %>
    </div>
</div>

app/views/code/share.html.erb
<div class="row">
    <div class="span12">
    <%= form_tag({:action=>"new", :controller=>"code"}, :name=>"code", :method=>"post", :multipart=>"true") do %>
        <div class="row">
            <div class="span7">
                <h2>The Code</h2>
                <%= text_field :snippet, :description, :class=>"span7", :placeholder=>"Description of the code" %>
                <%= text_field :snippet, :name, :class=>"span4", :placeholder=>"Name this code" %>
                <%= text_area :snippet, :source, :class=>"code-write span7", :placeholder=>"Your code", :rows=>"15" %>
            </div>
            <div class="span5">
                <span class="span5"><h2>The You</h2></span>
                <span class="span2">Nick</span>
                <%= text_field :code, :author, :class=>"span3", :placeholder=>"Not null, just a nick" %>
                <span class="span2">Email</span>
                <%= text_field :code, :email, :class=>"span3", :placeholder=>"Not null, won't be published" %>
                <span class="span2">Page</span>
                <%= text_field :code, :page, :class=>"span3", :placeholder=>"Personal Page(optional)" %>
                <span class="span2">Password</span>
                <%= text_field :code, :password, :class=>"span3", :placeholder=>"To manage code", :value=>"" %>
                <p class="span4">
                    <input class="btn-primary btn-large span2" type="submit" value="Commit" />
                    <input class="btn-primary btn-large span2" type="reset" value="Reset" />
                </p>
            </div>
        </div>
    <% end %>
    </div>
</div>

app/views/code/show.html.erb
<div class="row">
    <div class="span12">
        <div class="row">
            <div class="span12">
                <% if @snippet %>
                <div class="show-code">
                    <h2><%= @snippet[:name] %>
                    <% if !params[:code_id] %>
                        <small><%= link_to "Edit", edit_url(params[:id]) %></small>
                    <% else %>
                        <small><%= link_to "Lastest Version", show_url(params[:code_id]) %></small>
                    <% end %></h2>
                    <p><small>Description</small> <%= @snippet[:description] %></p>
                    <p><small>Author</small> 
                        <% if @code[:page] %>
                        <%= link_to @code[:author], @code[:page], :rel=>"nofollow" %>
                        <% else %>
                        <%= @code[:author] %>
                        <% end %>
                        <span class="version">
                            <small>Version</small> <%= link_to @snippet[:version], versions_url(@code) %>
                        </span> 
                    </p>
                    <p>
                        <small>Updated At</small> <%= @code[:updated_at] %>
                        <small>Created At</small> <%= @code[:created_at] %>
                    </p>
                    <%= show_code(@snippet[:source], @snippet[:language]) %>
                    
                </div>
                <hr />
                <div class="comment">
                    <h2>Comments</h2>
                    <div class="row">
                        <div class="span7">
                            <% if @comments %>
                                <% @comments.each_with_index do |c, index| %>
                                    <p>
                                        <%= gravatar_for c[:email], :size=>16 %>
                                        <% if c[:page] %>
                                            <%= link_to c[:nick], c[:page], :rel=>"nofollow" %>
                                        <% else %>
                                            <%= c[:nick] %>
                                        <% end %>
                                        <span class="comment_lev pull-right">#<%= index + 1 %></span>
                                    </p>
                                    <p>
                                        <small>Post at</small> <%= c[:created_at] %> <br />
                                    </p>
                                    <div class="comment_content"><%= markdown(c[:content]) %></div>
                                    <hr />
                                <% end %>
                            <% else %>
                            <p>There's no any comments yet</p>
                            <% end %>
                        </div>
                        <div class="span5">
                            <%= form_tag({:action=>"new", :controller=>"comment", :id=>params[:id]}, :name=>"comment", :method=>"post", :multipart=>"true") do %>
                                <%= label_tag :comment_email, "Email" %>
                                <%= text_field :comment, :email, :class=>"span3", :placeholder=>"Not null" %>
                                <%= label_tag :comment_nick, "Nick" %>
                                <%= text_field :comment, :nick, :class=>"span3", :placeholder=>"Not null" %>
                                <%= label_tag :comment_page, "Page"%>
                                <%= text_field :comment, :page, :class=>"span3", :placeholder=>"Personal Page" %>
                                <%= label_tag :comment_content, "Content" %>
                                <%= text_area :comment, :content, :class=>"span5", :rows=>5, :placeholder=>"Not null" %>
                                <p class="span4">
                                    <input type="submit" class="btn-primary span2" value="Submit" />
                                    <input type="reset" class="btn-primary span2" value="Reset" />
                                </p>
                            <% end %>
                        </div>
                    </div>

                    
                </div>
                <% else %>
                    <% if params[:code_id] %>
                    <h2>Sorry, code <%= params[:code_id] %> has no version <%= params[:id] %></h2>
                    <% else %>
                    <h2>Sorry, there's no code with id <%= params[:id] %></h2>
                    <% end %>
                <%= link_to "Back To Home", "/" %>
                <% end %>
            </div>
        </div>
    </div>
</div>

app/views/code/versions.html.erb
<div class="row page-body">
    <div class="span12">
        <div class="row">
            <div class="span8">
                <div class="row">
                    <% @snippets.reverse_each do |s| %>
                    <div class="span1">
                        <p class="version_tag">Version</p>
                        <p class="version_number">
                            <%= link_to s[:version], version_show_url(:code_id=>s[:code_id], :id=>s[:version]) %>
                        </p>
                    </div>
                    <div class="span7">
                        <p><small>Updated At</small> <%= s[:updated_at] %></p>
                        <p><%= s[:name] %></p>
                        <p><%= s[:description] %></p>
                        <hr />
                    </div>
                    <% end %> 
                </div>
            </div>
            <div class="span4">
                <h2 class="info">Author Info</h2>
                <p class="info">
                    <% if @code[:page] %>
                    <a href=<%= @code[:page] %>><%= gravatar_for @code[:email], :size=>48 %></a><br />
                    <%= link_to @code[:author], @code[:page] %>
                    <% else %>
                    <%= gravatar_for @code[:email], :size=>48 %><br />
                    <%= @code[:author] %>
                    <% end %>
                </p>
            </div>
        </div>
    </div>
</div>

app/views/home/about.html.erb
<h2>About CodeShare</h2>
<p>A samll website for showing code snippets, homework of my Ruby class</p>
<p>Using the following</p>
<ul>
    <li>Ruby on rails</li>
    <li>Bootstrap</li>
    <li>Github for version control</li>
    <li>Heroku for release</li>
</ul>
<p>Source Code is at <a href="http://github.com/iEverX/codeshare">Here</a> </p>

<h2>About Me</h2>
<p>Ever, or iEverX, is me</p>
<p>Personal Website is <a href="http://blog.EverCoding.net" rel="nofollow">EverCoding</a></p>
<p>More on <a href="http://blog.EverCoding.net/about.html">Personal Website About Page</a></p>

app/views/home/index.html.erb
<div class="row page-body">
    <div class="span12">
        <div class="row">
            <div class="span5 index_show">
                <h2>The latest code</h2>
                <div class="row part_title">
                    <div class="span1">ID</div>
                    <div class="span4">Description</div>
                </div>
                <% @latest.each do |snippet| %>
                <hr class="index_hr" />
                <div class="row">
                    <div class="span1"><%= link_to snippet[:code_id], show_url(snippet[:code_id]) %></div>
                    <div class="span4"><%= snippet[:description] %></div>
                </div>
                <% end %>
                </hr />
            </div>
            <div class="span7 index_show">
                <h2>The hottest code</h2>
                <div class="row part_title">
                    <div class="span1">ID</div>
                    <div class="span1">Comments</div>
                    <div class="span5">Description</div>
                </div>
                <% @hottest.each do |snippet, comment_count| %>
                <hr class="index_hr" />
                <div class="row">
                    <div class="span1"><%= link_to snippet[:code_id], show_url(snippet[:code_id]) %></div>
                    <div class="span1"><%= comment_count %></div>
                    <div class="span5"><%= snippet[:description] %></div>
                </div>
                <% end %>
                </hr />
            </div>

        </div>
    </div>
</div>

app/views/home/list.html.erb
<div class="page-body">
    <h1>The Code List</h1>
    <hr />
    <div class="row part_title">
        <div class="span1">ID</div>
        <div class="span2">Author</div>
        <div class="span2">Name</div>
        <div class="span7">Description</div>
    </div>
    <hr />
    <% @codes.each do |snippet, code| %>
    <div class="row">
        <div class="span1">
            <%= link_to code[:id], show_url(code[:id]) %>
        </div>
        <div class="span2">
            <%= gravatar_for code[:email], :size=>16 %>
            <% if code[:page] %>
                <%= link_to code[:author], code[:page], :rel=>"nofollow" %>
            <% else %>
                <%= code[:author] %>
            <% end %>
        </div>
        <div class="span2"><%= snippet[:name] %></div>
        <div class="span7"><%= snippet[:description] %></div>
    </div>
     <hr class="index_hr" />
    <% end %>
    
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>CodeShare</title>
  <%= stylesheet_link_tag 'bootstrap.min.css' %> 
  <%= stylesheet_link_tag 'style.css' %>
  <style type="text/css">
    body { background-color: #eee; }
  </style>
</head>
<body>
    <div class="navbar" id="page-top">
        <div class="navbar-inner">
            <div class="container">
                <a class="brand" href="/">CodeShare</a>
                <ul class="nav">
                    <li><a href="/list">List</a></li>
                    <li><a href="/about">About</a></li>
                </ul>
                <ul class="nav pull-right share"><li><a href="/share">Share Code</a></li></ul>
                <ul class="nav pull-right">
                    <li>                
                        <form action="/code/show" method="post" class="navbar-search">
                            <input class="search-query" name="id" type="text" placeholder="The id to view" />
                        </form>
                    </li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container">
        <div class="mycontent">
            <div class="page-header">
                <h1>CodeShare <small>Just share</small></h1>
            </div>
<%= yield %>
        </div>
        <footer>
            <p>Powered By <a href="http://blog.EverCoding.net">Ever</a><p>
            <p>using Ruby on Rails and Bootstrap</p>
        </footer>
    </div>
</div>      
</body>
</html>